# Generated by Django 5.1.2 on 2024-10-25 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_image_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
