# Generated by Django 5.1.2 on 2024-10-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_temporaryuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporaryuser',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='temporaryuser',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
